### PR TITLE
fix(issuedescription): fix issue display lists in IssueDescription

### LINKED ISSUE #2971: Issue description not displayed in UI when text starts with ordered list (e.g. "1.")
## Description

When creating an issue in Seerr, if the description text starts with an ordered list item (e.g. `1. some text`), the description field is not displayed in the Seerr UI on the issue detail page.

## Steps to Reproduce

1. Go to any media item and report an issue
2. In the description field, type text starting with `1.` (e.g. `1. Fehlermeldung mit Listung`)
3. Submit the issue
4. Open the issue detail page

## Expected Behavior

The description is displayed as entered.

## Actual Behavior

The description field appears empty on the issue detail page.

## Additional Context

The data is stored correctly in the database — via `GET /api/v1/issue/{id}` the text is present in `comments[0].message`. This is purely a frontend rendering issue: Seerr renders `comments[0]` as the description, but the markdown renderer fails to display the text when it begins with an ordered list syntax (`1. `).

Tested with two issues on the same instance:
- Issue #15: description `Fehlermeldung ohne Listung` → displayed correctly
- Issue #16: description `1. Fehlermeldung mit Listung` → not displayed in UI

Both have `message: null` on the API level; the description is stored identically as `comments[0].message` in both cases.

### Version

3.2.0 (commit e4ee71ae)

### Steps to Reproduce

1. Open any media item (movie or TV show)
2. Click "Report an Issue"
3. Select an issue type (e.g. Audio)
4. In the description field, enter text that starts with an ordered list item, e.g. `1. Some description text`
5. Submit the issue
6. Open the issue detail page
→ The description field is empty

Repeat with the same text but without the leading `1.` (e.g. `Some description text`) → the description is displayed correctly.

### Screenshots

_No response_

### Logs

```shell
# Issue #15 — description WITHOUT ordered list → displayed correctly
GET /api/v1/issue/15
message: None
comments[0].message: "Some description text"

# Issue #16 — description WITH ordered list → NOT displayed in UI
GET /api/v1/issue/16
message: None
comments[0].message: "1. Some description text"

# Seerr log at time of issue creation (no payload details logged)
2026-04-29T08:46:53.038Z [info][Notifications]: Sending notification(s) for ISSUE_CREATED {"subject":"Movie Title (2026)"}
2026-04-29T08:46:53.038Z [debug][Notifications]: Sending webhook notification {"type":"ISSUE_CREATED","subject":"Movie Title (2026)"}
```

### Platform

desktop

### Database

SQLite (default)

### Device

Microsoft Edge 148 

### Operating System

Ubuntu 24.04.4 LTS (Docker)

### Browser

Edge (latest stable)

### Additional Context

- Seerr is running in Docker on Ubuntu 24.04.4 LTS
- The issue description is not stored in a dedicated `message` field on the issue — it is always saved as `comments[0].message` in the SQLite database (`issue_comment` table). This applies to both working and broken cases.
- The webhook notification sent by Seerr for `ISSUE_CREATED` also contains an empty `message` field in both cases, confirming this is not input-specific but consistent Seerr behavior.
- The rendering failure is reproducible 100% of the time when the description starts with `1. ` (ordered list). Other text without list syntax is always displayed correctly.
- Tested via browser UI (Windows 11/Edge) and confirmed via direct SQLite query and REST API.

### Search Existing Issues

- [x] Yes, I have searched existing issues.

### Code of Conduct

- [x] I agree to follow Seerr's Code of Conduct

### PR DESCRIPTION
**Pull request by gauthier-th**
## Description

The `allowedElements` list was missing basic markdown elements for lists (ordered and unordered).
This list in IssueDescription is now synced with the one in IssueComment.

- Fix #2971
- Re #1638

## How Has This Been Tested?

Create an issue with a description starting with with `1. ` or `- `

## Screenshots / Logs (if applicable)

Before:
image

After:
image

## Checklist:

- [x] I have read and followed the contribution [guidelines](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md).
- [x] Disclosed any use of AI (see our [policy](https://github.com/seerr-team/seerr/blob/develop/CONTRIBUTING.md#ai-assistance-notice))
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] Successful build `pnpm build`
- [ ] Translation keys `pnpm i18n:extract`
- [ ] Database migration (if required)

## Summary by CodeRabbit

* **Bug Fixes**
  * Enhanced markdown rendering in issue descriptions to support lists while adjusting content display.

### CODE REVIEW

**Review by M0NsTeRRR — APPROVED** [review]

File: src/components/IssueDetails/IssueDescription/index.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ const IssueDescription = ({
       ) : (
         <div className="prose mt-4">
           <ReactMarkdown
-            allowedElements={['p', 'img', 'strong', 'em']}
```
Comment (0xSysR3ll) [inline src/components/IssueDetails/IssueDescription/index.tsx:150]: Why was `img` removed ?

Comment (gauthier-th) [reply src/components/IssueDetails/IssueDescription/index.tsx:150]: Because we can't upload image in the issue description anyway

Comment (0xSysR3ll) [reply src/components/IssueDetails/IssueDescription/index.tsx:150]: Fair enough !

**Review by 0xSysR3ll — APPROVED** [review]
